version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:21.6.0
  docker-executor:
    docker:
      - image: cimg/base:2024.01
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: node --version
  say_hello:
    executor: docker-executor
    steps:
      - run: echo "Say hello to YAML!"
workflows:
  version: 2
  greet_user:
    jobs:
      - say_hello
            # filters:
            #   branches:
            #     only: main
