version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.6.0
    steps:
      - checkout
      - run: node --version
      - run: echo "Say hello to YAML!"

  say_hello:
    steps:
      - run: echo "Say hello to YAML!"

workflows:
  # Name of workflow
  greet_user:
    # List of jobs that will run
    jobs:
      - say_hello